<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DeleteImages.aspx.cs" Inherits="MyWebFormCases.gridview3.DeleteImages" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" DataKeyNames="ProductID"  AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting">
            <Columns>
                <asp:BoundField DataField="ProductID" HeaderText="ProductID" InsertVisible="False" ReadOnly="True" SortExpression="ProductID" />
                <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                <asp:TemplateField HeaderText="images">
                    <ItemTemplate>
                     
                        <asp:Image ID="Image1" runat="server" ImageUrl='<%# "/images/WingtipToysBak/"+Eval("ImagePath") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
                <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" />
                <asp:BoundField DataField="CategoryID" HeaderText="CategoryID" SortExpression="CategoryID" />
            </Columns>
        </asp:GridView>
      
    </form>
</body>
</html>
