<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="SaveDatatableInSession.aspx.cs" Inherits="MyWebFormCases.gridview3.SaveDatatableInSession" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" DataKeyNames="id"></asp:GridView>


   
    </form>
</body>
</html>
