//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebFormCases.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employ", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employ : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EmpIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int EmpId {
            get {
                return this.EmpIdField;
            }
            set {
                if ((this.EmpIdField.Equals(value) != true)) {
                    this.EmpIdField = value;
                    this.RaisePropertyChanged("EmpId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string FName {
            get {
                return this.FNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FNameField, value) != true)) {
                    this.FNameField = value;
                    this.RaisePropertyChanged("FName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.ArrayDataSoap")]
    public interface ArrayDataSoap {
        
        // CODEGEN: Generating message contract since element name GetDataResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        MyWebFormCases.ServiceReference2.GetDataResponse GetData(MyWebFormCases.ServiceReference2.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWebFormCases.ServiceReference2.GetDataResponse> GetDataAsync(MyWebFormCases.ServiceReference2.GetDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetData", Namespace="http://tempuri.org/", Order=0)]
        public MyWebFormCases.ServiceReference2.GetDataRequestBody Body;
        
        public GetDataRequest() {
        }
        
        public GetDataRequest(MyWebFormCases.ServiceReference2.GetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDataRequestBody {
        
        public GetDataRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWebFormCases.ServiceReference2.GetDataResponseBody Body;
        
        public GetDataResponse() {
        }
        
        public GetDataResponse(MyWebFormCases.ServiceReference2.GetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public MyWebFormCases.ServiceReference2.Employ[] GetDataResult;
        
        public GetDataResponseBody() {
        }
        
        public GetDataResponseBody(MyWebFormCases.ServiceReference2.Employ[] GetDataResult) {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ArrayDataSoapChannel : MyWebFormCases.ServiceReference2.ArrayDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ArrayDataSoapClient : System.ServiceModel.ClientBase<MyWebFormCases.ServiceReference2.ArrayDataSoap>, MyWebFormCases.ServiceReference2.ArrayDataSoap {
        
        public ArrayDataSoapClient() {
        }
        
        public ArrayDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ArrayDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArrayDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ArrayDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWebFormCases.ServiceReference2.GetDataResponse MyWebFormCases.ServiceReference2.ArrayDataSoap.GetData(MyWebFormCases.ServiceReference2.GetDataRequest request) {
            return base.Channel.GetData(request);
        }
        
        public MyWebFormCases.ServiceReference2.Employ[] GetData() {
            MyWebFormCases.ServiceReference2.GetDataRequest inValue = new MyWebFormCases.ServiceReference2.GetDataRequest();
            inValue.Body = new MyWebFormCases.ServiceReference2.GetDataRequestBody();
            MyWebFormCases.ServiceReference2.GetDataResponse retVal = ((MyWebFormCases.ServiceReference2.ArrayDataSoap)(this)).GetData(inValue);
            return retVal.Body.GetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWebFormCases.ServiceReference2.GetDataResponse> MyWebFormCases.ServiceReference2.ArrayDataSoap.GetDataAsync(MyWebFormCases.ServiceReference2.GetDataRequest request) {
            return base.Channel.GetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWebFormCases.ServiceReference2.GetDataResponse> GetDataAsync() {
            MyWebFormCases.ServiceReference2.GetDataRequest inValue = new MyWebFormCases.ServiceReference2.GetDataRequest();
            inValue.Body = new MyWebFormCases.ServiceReference2.GetDataRequestBody();
            return ((MyWebFormCases.ServiceReference2.ArrayDataSoap)(this)).GetDataAsync(inValue);
        }
    }
}
