//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyWebFormCases.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.myWebServiceSoap")]
    public interface myWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name value from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDate", ReplyAction="*")]
        MyWebFormCases.ServiceReference1.getDateResponse getDate(MyWebFormCases.ServiceReference1.getDateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getDate", ReplyAction="*")]
        System.Threading.Tasks.Task<MyWebFormCases.ServiceReference1.getDateResponse> getDateAsync(MyWebFormCases.ServiceReference1.getDateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDate", Namespace="http://tempuri.org/", Order=0)]
        public MyWebFormCases.ServiceReference1.getDateRequestBody Body;
        
        public getDateRequest() {
        }
        
        public getDateRequest(MyWebFormCases.ServiceReference1.getDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public getDateRequestBody() {
        }
        
        public getDateRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public MyWebFormCases.ServiceReference1.getDateResponseBody Body;
        
        public getDateResponse() {
        }
        
        public getDateResponse(MyWebFormCases.ServiceReference1.getDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getDateResult;
        
        public getDateResponseBody() {
        }
        
        public getDateResponseBody(string getDateResult) {
            this.getDateResult = getDateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface myWebServiceSoapChannel : MyWebFormCases.ServiceReference1.myWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class myWebServiceSoapClient : System.ServiceModel.ClientBase<MyWebFormCases.ServiceReference1.myWebServiceSoap>, MyWebFormCases.ServiceReference1.myWebServiceSoap {
        
        public myWebServiceSoapClient() {
        }
        
        public myWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public myWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public myWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MyWebFormCases.ServiceReference1.getDateResponse MyWebFormCases.ServiceReference1.myWebServiceSoap.getDate(MyWebFormCases.ServiceReference1.getDateRequest request) {
            return base.Channel.getDate(request);
        }
        
        public string getDate(string value) {
            MyWebFormCases.ServiceReference1.getDateRequest inValue = new MyWebFormCases.ServiceReference1.getDateRequest();
            inValue.Body = new MyWebFormCases.ServiceReference1.getDateRequestBody();
            inValue.Body.value = value;
            MyWebFormCases.ServiceReference1.getDateResponse retVal = ((MyWebFormCases.ServiceReference1.myWebServiceSoap)(this)).getDate(inValue);
            return retVal.Body.getDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MyWebFormCases.ServiceReference1.getDateResponse> MyWebFormCases.ServiceReference1.myWebServiceSoap.getDateAsync(MyWebFormCases.ServiceReference1.getDateRequest request) {
            return base.Channel.getDateAsync(request);
        }
        
        public System.Threading.Tasks.Task<MyWebFormCases.ServiceReference1.getDateResponse> getDateAsync(string value) {
            MyWebFormCases.ServiceReference1.getDateRequest inValue = new MyWebFormCases.ServiceReference1.getDateRequest();
            inValue.Body = new MyWebFormCases.ServiceReference1.getDateRequestBody();
            inValue.Body.value = value;
            return ((MyWebFormCases.ServiceReference1.myWebServiceSoap)(this)).getDateAsync(inValue);
        }
    }
}
